### ISSUE TITLE
自行部署后尝试登录操作会提示 “jwt secretKey is required”

### ISSUE THREAD

**Issue by 1834423612** [lnbiuc/blog-next-view#41]
请大佬看看，谢谢！！

当我部署以后尝试登录就会不停提示 `jwt secretKey is required`

不会用这个MongoDB，以前一直是用的MySQL，尝试提前先创建了一个用户，但依旧会有这个jwt加密的东西报错。

![image](https://github.com/lnbiuc/blog-next-view/assets/49981661/cf23e2b3-03bb-463c-a20b-7f6140aeb8fb)

**Comment by 1834423612** [comment]
令人费解的是经过我多次尝试本地和云端部署，相同的代码竟然会有两种不同的报错内容，（我尝试随机设了一个jwt key）
另一个部署的报错：
`MongooseError: Operation `users.findOne()` buffering timed out after 10000ms`

![image](https://github.com/lnbiuc/blog-next-view/assets/49981661/7620d73c-125f-4885-8bac-64f99b13e31f)

**Comment by lnbiuc** [comment]
环境变量里填一下JWT_SECRET_KEY

**Comment by lnbiuc** [comment]
> 令人费解的是经过我多次尝试本地和云端部署，相同的代码竟然会有两种不同的报错内容，（我尝试随机设了一个jwt key）
> 
> 另一个部署的报错：
> 
> `MongooseError: Operation `users.findOne()` buffering timed out after 10000ms`
> 
> 
> 
> ![image](https://github.com/lnbiuc/blog-next-view/assets/49981661/7620d73c-125f-4885-8bac-64f99b13e31f)
> 
> 

这个因为请求超时或者数据库连接超时了，你看下

**Comment by 1834423612** [comment]
尝试更换了一个腾讯云服务器和另一个MongoDB官方的服务器，依旧是提示超时（目前使用美国原生网，不应该出现链接超时等情况）
DB链接信息如下（测试后会删机）：`mongodb+srv://admin:qJKLFiSojlhh2Xuv@kjch.al080id.mongodb.net/?retryWrites=true&w=majority&appName=kjch`

对于MongoDB这方面是一窍不通的小白😣谢谢！！！

![image](https://github.com/lnbiuc/blog-next-view/assets/49981661/bd9d55e5-701d-4937-942b-647a1cf7a2db)
![image](https://github.com/lnbiuc/blog-next-view/assets/49981661/2000cc1d-e7f3-45d0-9be0-b474c2c8ead5)

**Comment by 1834423612** [comment]
终于成功了😫是MongoDB的问题，没有设置权限（官方数据库），之前几次是未知问题导致的鉴权失败。

谢谢您！！！！
